### ISSUE TITLE
The website is not working

### ISSUE THREAD

**Issue by slarrain** [vrutkovs/github-review-dashboard#58]
* Github Review Dashboard version:
N/A
* Python version:
N/A
* Operating System:
Ubuntu

### Description

The website provided is not working: http://github-review.aracan.ga/

### What I Did

Click on the website link

**Comment by vrutkovs** [comment]
Thanks, the site was taken down as it didn't support HTTPS properly. Now its resolved and running on https://github-review.aracan.ga
